# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('externalId', models.CharField(blank=True, default='', max_length=100)),
                ('agentId', models.CharField(blank=True, default='', max_length=100)),
                ('startDate', models.DateField()),
                ('numberOfEmails', models.IntegerField()),
                ('numberOfCalls', models.IntegerField()),
                ('averageDuration', models.FloatField()),
                ('isResolved', models.BooleanField(default=False)),
                ('nps', models.FloatField()),
            ],
            options={
                'ordering': ('externalId',),
            },
        ),
    ]
