# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='averageHoldingDuration',
            field=models.FloatField(default=0.5),
        ),
    ]
