# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20171004_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='averageDuration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='averageHoldingDuration',
            field=models.IntegerField(default=30),
        ),
    ]
